import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";


const roboto = Roboto({ subsets: ['latin'] ,weight: ['400', '700'],});



export const metadata: Metadata = {
  title: "Policybazaar",
  description: "Generated by Classic",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        {/* <HeaderPage /> */}
       

        {children}
        
        {/* <FooterPage /> */}
      </body>
    </html>
  );
}
